blank.ts
=> Add a blank Dangerfile

peril.settings.json
Updates Reaction repo url from `reaction-force` to `reaction`. 
cc @orta
=> Update repo url

README.md, ambient.d.ts, danger/new_rfc.ts, package.json, peril.settings.json, tsconfig.json, yarn.lock
This should ping our slack channel when we get create an RFC for a new org-wide peril rule.
=> Add support for slacking when an RFC is announced

spellcheck.json
See: https://github.com/artsy/ohm/pull/433
=> Adds Memcached and localhost.

org/all-prs.ts, yarn.lock
This adds:
* A check for ensuing we have assignees
* A check for ensuing that the PR body has some text
=> Adds body checks, and PR assignee checks 

.travis.yml, README.md, org/all-prs.ts, package.json, tests/rfc_13.test.ts, tests/rfc_5.test.ts, tests/utils.ts, yarn.lock
This makes it possible to individually test out a rule - while also handling one of Peril's current issues around not being able to handle relative require statements.
=> Adds a testing infrastructure for danger rules

.vscode/settings.json, org/all-prs.ts, package.json, tests/rfc_13.test.ts, tests/rfc_16.test.ts, tests/rfc_5.test.ts, tests/utils.ts, tsconfig.json
I think the new tactic is going to have to be using convention to change the amount of code eval'd - will explain after my paring session
=> Attempt to cover tests for 16

org/all-prs.ts, tests/rfc_13.test.ts, tests/rfc_16.test.ts, tests/rfc_5.test.ts
* uses both modified/created
* uses a GH API to get all the root folder contents, meaning less API requests 👍 
* Removes unused after closures, don't think they need to exist
=> Simplify rfc 16 a bit

org/closed-prs.ts, peril.settings.json, tests/rfc_33.test.ts
Adds the ability for a label to send slack alerts to particular dev channels in slack.
=> Adds an rfc for issue #33

org/all-prs.ts
after naïvely copying this code for my own purposes, I tested it with a
PR where I managed to submit a PR with a NULL body
The way this code failed, was to comment the exception into the PR.
=> check pr.body is null before trying to check length

org/closed-prs.ts, package.json, tests/rfc_33.test.ts, yarn.lock
I had shipped a failing build ( see #36 ) - so now we run prettier + the jest tests for the changed files.
=> Run tests + prettier on commit

README.md
Based on some discussion in our collective Slack
=> Update the RFC template to ask for a reference to a slack convo

org/closed-prs.ts
Context for the discussion in slack: https://artsy.slack.com/archives/C0C4AJ1PF/p1516992065000009
=> Sends a notification to auctions-dev when an auctions related PR is merged

wallaby.js
Notes: https://github.com/artsy/artsy.github.io/issues/406
=> Add support for wallaby js

peril.settings.json
Spellchecking flagging too many false positives
=> Ignore Hokusai

README.md, org/all-prs.ts, org/closed-prs.ts, org/new-release.ts, package.json, peril.settings.json
I migrated the repo a while ago, this changes the settings
=> Peril settings instead of artsy-danger

README.md, peril.settings.json, tasks/daily-license-check.ts
Mainly to restart the installation
=> Gives the right zero message for license checks

peril.settings.json
This lets the peril config know to look for the dangerfile
=> Notes that a dangerfile exists on exchange

peril.settings.json
Sibling PR of https://github.com/artsy/force/pull/2889
=> Adds force to have an extra dangerfile run on PRs with the dangerfile in force

org/mergeOnGreen.ts, org/rfc/scheduleRFCsForLabels.ts, tests/rfc_40.test.ts
Adds a note on how to resolve an RFC on the final reminder
=> Adds a link to the RFC resolver after a week

org/jira/pr.ts
I'm gonna see if it will work with just my API token instead of a proper bot account.
=> Tries logging into jira via the env var JIRA_ACCESS_TOKEN

peril.settings.json, tasks/standupReminder.ts
Handles some of the weirder JS constraints from peril - and gives us the ability to just run the slackup
=> Fix the slackup note

README.md
=> Adds link to Peril Dashboard

peril.settings.json, tasks/closedSourceRationaleCheck.ts, tests/closedSourceRationaleCheck.test.ts
Paired with @ashfurrow on this some today and pushing my WIP for initial feedback.
Fixes https://github.com/artsy/README/issues/131.
=> Add check for closed source rationale

tasks/closedSourceRationaleCheck.ts
By adding a little more content to the issue, we're helping people comply with the check and being a little more friendly.
h/t @orta
=> Improve the text of the issue

peril.settings.json
Adds support for running https://github.com/artsy/metaphysics/pull/1640
=> Adds support for running the schema checks on MP

org/jira/pr.ts
Reverts artsy/peril-settings#119
See discussion in that PR for rationale.
=> Revert "Use normal import for utils"

README.md
I can never seem to remember it, so let's put it in the readme 😅
=> Adds link to Dashboard

README.md
Adds point people, project status, and a link to CI. We've become the _de facto_ point people for this, so let's formalize it 👍
=> Adds point people, project status, and a link to CI

README.md
=> Updates Dashboard URL

org/allPRs.ts, tests/deploySummary.test.ts
#minor whoops, the link to PR's was wrong 😅
=> @mzikherman => [deploySummary] Correct link for PRs

package.json, tasks/standupReminder.ts, tests/standupReminder.test.ts, yarn.lock
This is no longer necessary since OpsGenie has become our source of truth for our on-call schedule.
=> Removes Google Calendar lookup from standup reminders

org/jira/utils.ts, peril.settings.json, tests/rfc_74.test.ts, tsconfig.json
This work is based on the RFC here:https://github.com/artsy/README/issues/274
=> JIRA ticket regex update

peril.settings.json
Let's see how this goes! Will merge when MP has the script.
=> @mzikherman => Add Peril task to MP PRs for a schema check against Reaction

package.json, yarn.lock
=> @mzikherman => [Package] Add @graphql-inspector/core for schema diffs on MP

tasks/standupReminder.ts, tests/standupReminder.test.ts
Just bumping this from 11:30 → 12:00 noon, to match reality 😄
=> Update the big standup time that's displayed in Slack 

org/allPRs.ts, tests/rfc_16.test.ts
@MounirDhahri and I removed eigen from the changelog checking.
https://www.notion.so/artsy/Mounir-Pavlos-remove-Danger-Peril-changelog-check-in-Eigen-add-checkbox-to-PR-template-dfbb453196d64f7c9f792705e4a45072
Could we have disabled this inside the eigen repo? 🤔
=> Skip eigen for changelog

org/rfc_237.ts
Small copy update for the RFC 327 check.
=> feat: update copy for RFC 327 (pr / commit formatting) check

README.md
- Point People: Remove Ash / Add Devon
- Update dashboard URLS
- Update GitHub repository URLS
=> docs: Update README documentation

README.md
cc @dblandin given that you're the other point person here 😄
=> chore: Remove me as point person

README.md, dangerfile.ts, org/allPRs.ts, org/rfc/scheduleRFCsForLabels.ts, tasks/compareSchemas.ts, tasks/standupReminder.ts, tests/dangerfile.test.ts, tests/rfc_40.test.ts, tests/standupReminder.test.ts
Updates references from master -> main
=> chore: Update references master -> main

org/allPRs.ts
Adding force / palette to the rule
=> feat(allPRs): Add force/palette to semantic commit rule

org/allPRs.ts
Adds volt v2 to list.
cc @artsy/negotiate-devs
=> feat(semantic-titles): Add volt-v2 to list
