artsy/peril-settings

org/all-prs.ts
tests/rfc_16.test.ts

Broken by #23. For the root of the repo, path needs to be `''`, and returns an array wrapped in the `data` key.

Fixes getContent call to GitHub.

---

org/all-prs.ts
tests/rfc_7.test.ts

Fixes #7, based on [this work from Orta](https://github.com/danger/danger-js/issues/180#issuecomment-308386682). Possible addition: translate from shorthand to longhand labels (so a commit message like `[MSG] Implements inbox` would match the `Messaging` label. I'll take a look later today. 
There's probably some code golfing to do, so don't be shy about pointing out alternative syntax etc!

Implements RFC 7

---

org/all-prs.ts
tests/rfc_7.test.ts

Re: #26 - I spotted that additional commits would trigger every events. You obviously can't add the same label twice, but GitHub still triggers an event in the stream, so that will get annoying quickly. 
I added some typing further up the mapping system, so that they flow through the mapping correctly 👍

Don't allow duplication of issues inside a PR

---

peril.settings.json

It's being used for PRs, but not by an engineering team, so they shouldn't be held to the same rigor (today ;) )
/cc @mdole @cfinsness

Update peril.settings.json to remove artsy/clouds

---

spellcheck.json

It was invoked erroneously here: https://github.com/artsy/apogee/pull/5#issuecomment-359873172

Adds my GH username to list.

---

org/all-prs.ts
tests/rfc_16.test.ts

I occasionally see this check happening on closed PRs, which it definitely shouldn't do.

Updates RFC16 to not run on a closed PR

---

peril.settings.json

They shouldn't be held up to the same level of process as engineering. /cc @briansw

Update peril.settings.json to ignore the design repo

---

org/all-prs.ts
org/closed-prs.ts
org/new-release.ts
tests/rfc_13.test.ts
tests/rfc_33.test.ts
tests/rfc_5.test.ts
tests/rfc_53.test.ts

Now that we're moving to peril-staging, we can use the new  default export feature of a Dangerfile - https://github.com/danger/peril/pull/247
This vastly simplifies each dangerfile, and makes testing basically the same as a normal JS file 👍

Update settings repo to new peril format

---

org/markAsMergeOnGreen.ts
org/mergeOnGreen.ts
peril.settings.json
tests/rfc_10.test.ts

Fixes #10 - Well tested.
Adds merge on green - something I've been using for the last [three weeks on danger-js](https://github.com/danger/danger-js/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Merge+On+Green%22) successfully.

Adds merge on green support to the Artsy org

---

danger/new-rfc.ts
org/new-release.ts
package.json
peril.settings.json
tests/rfc_40.test.ts
tests/rfc_53.test.ts
yarn.lock

- `peril.runTask` is now running on a different server than the code is being executed on, so it needs to be switched into an async task.
- Moved more of the event based Dangerfiles to use `export default` for their runtime
- Adds node-fetch to the types

Updates the RFC code to handle the new async version inside a sandbox

---

org/all-prs.ts
tests/rfc_16.test.ts

Looks like the GitHub API wants you to use [tree SHAs](https://developer.github.com/v3/git/trees/#get-a-tree), not branches for file tree lookups. The RFC now uses the base merge sha (and base ref for everything else) to check if a changelog exists on the other repo.
Should fix https://github.com/artsy/diffusion/runs/2579570 on https://github.com/artsy/diffusion/pull/107

Updates the changelog check to include a sha instead of master

---

tasks/daily-license-check.ts

We want to reduce the number of false-positives in https://github.com/artsy/potential/issues/157 - this means only repos we own and repos updated this year get included.

Adds a check for the current year to the license checker, and avoids forks

---

org/all-prs.ts
tests/rfc_16.test.ts

Convention in mobile repos is to allow skipping the changelog check ( [eigen](https://github.com/artsy/eigen/blob/master/Dangerfile#L4-L7) / [emission](https://github.com/artsy/emission/blob/master/dangerfile.ts#L18-L21) ) - this allows Peril to also have the same rules.

Allows the CHANGELOG check to be skipped via #trivial

---

org/mergeOnGreen.ts
tests/rfc_10.test.ts

This updates the tense and format of merge commits to match Github's. Including the PR # is helpful because Github will auto-link that. I'd ideally like to include the `... from <repo>/<branch>` part as well, but it wasn't immediately obvious how to determine this correctly from Github's API response.
Incidentally, matching Github's format will allow some of our projects' automated release emails to better identify the PRs corresponding to commits.

Include PR number in commit title when merging on green

---

peril.settings.json

We want to just use Peril instead of both Danger ruby and Peril in Volt.

Add Volt to Peril repo

---

org/rfc/addRFCToNewIssues.ts
org/rfc/scheduleRFCsForLabels.ts
package.json
peril.settings.json
tests/rfc_40.test.ts

Allows a human to set the label on an issue (in the case like 
https://github.com/artsy/README/issues/49 ) where I forgot to include RFC in the title when the issue was created. 
This allows anyone to set up and RFC process with just the label.

Allows a human to set an RFC tab and have Peril work with it

---

org/markAsMergeOnGreen.ts
peril.settings.json
tests/rfc_10.test.ts

Our organization's Peril settings support marking a Pull Request for an automated merge once commit statuses pass when requested from a comment on the Pull Request. This commit updates our Peril settings to also respond to the body of a submitted Pull Request Review, if provided.
The `org/markAsMergeOnGreen` rule currently supports a match against [IssueComment][issue-comment-event] GitHub webhook events. This commit updates the rule to support [PullRequestReview][pr-review-event] GitHub webhook events as well.
[pr-review-event]: https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent
[issue-comment-event]: https://developer.github.com/v3/activity/events/types/#issuecommentevent
Addresses https://github.com/artsy/peril-settings/issues/81

Support requests for merge on green behavior from a Pull Request review

---

repos/reaction/addPatchLabel.ts

Label messages need to go straight to the point:

Make the labels description much smaller

---

org/addPatchLabel.ts
peril.settings.json
tests/rfc_reaction_1095.test.ts

Related https://github.com/artsy/reaction/pull/1779
Moves `addPatchLabel` into the global namespace so that repos containing an `.autorc` can be evaluated.

Make addPatchLabel global

---

package.json
peril.settings.json
tasks/standupReminder.ts
tests/standupReminder.test.ts
yarn.lock

This PR automates a task I've been doing manually for most of the year, which is reminding the on-call engineers that it's their responsibility to run standup. 
Still left to do:

Automates reminders to on-call engineers that they are running standup

---

org/mobilePRsForbidForks.ts
peril.settings.json
tests/mobilePRsForbidForks.test.ts

We had a [PR](https://github.com/artsy/eigen/pull/2757) this week that got merged into Eigen despite failing unit tests because Eigen doesn't build PRs on forks. This is a historical quirk; the "mobile team" has always used branches and the rest of Artsy uses forks. Rather than rebuild a half decade of mobile repo tooling, this PR adds a Peril rule that will fail builds from Artsy staff who submit PRs from forks on mobile repos (and it will warn on PRs from OSS contributors).

Forbids PRs from forks on mobile repos

---

org/mergeOnGreen.ts

This updates the merge on green commit message to be the PR title with the PR number in parenthesis. This update will make the changelogs generated by `auto` have more useful entries. This is the same format that is used if you do a squash merge in github. 
Also, a minor thing. This removes any `@user => ` prefixes from PR titles.

Change mog commit to be title of PR

---

org/jira/pr.ts
peril.settings.json
tasks/standupReminder.ts
tasks/supGP.js
tests/standupReminder.test.ts

Some teams want a weekly mini-sup just for their team, this is the infra so I can iterate on that without making a million PRs. 
Also moves `process.env` code to `peril.env` because I'll be removing that feature in https://github.com/danger/peril/pull/417 because lambdas can be warm launched unlike in the past.

Starts a new sup recurring task

---

org/newEigenBeta.ts
package.json
peril.settings.json
tests/newEigenBeta.test.ts
yarn.lock

As discussed back in [December's Front-End iOS Practice meeting](https://www.notion.so/artsy/December-7-2018-Meeting-Notes-a1428a9d88924551883e9c9eebfdbc97), we want to automate a notification on Jira tickets when changes related to those tickets get deployed in an Eigen beta. There was interest in doing this for Force as well, but I wanted to keep the scope limited for the initial implementation.
This is a WIP because I need to write some unit tests. I wanted to get my changes up for some early feedback. I found the [existing implementation](https://github.com/danger/peril-settings/blob/b306662628f1a4c5c4ebc5f0531e15561fe60fa5/org/new_tag.ts#L12-L64) that @orta linked to very helpful.

Notifies Jira tickets when related Eigen betas are deployed

---

org/jira/pr.ts
package.json
yarn.lock

In local discovery we use different labels for the "in review", and "merged" stages. So Peril wouldn't auto move stuff for us when you see the blue "Jira Synced" label, now it does.

Handle the sprint titles in local disco

---

tasks/standupReminder.ts
tests/standupReminder.test.ts

We've started to trial OpsGenie to schedule on-call rotations. This commit updates our weekly standup reminder to use on-call participants from OpsGenie, if available. This should not overlap with our existing Google Calendar-backed scheduling.
This updates requires two new environment variables:
- `OPSGENIE_SCHEDULE_ID`
- `OPSGENIE_API_KEY`
RFC: https://github.com/artsy/README/issues/184

Update standup reminder to pull on-call participants from OpsGenie

---

org/allPRs.ts
tests/rfc_13.test.ts

We're pretty consistently getting peril failures in reaction on renovate PRs where peril claims there's no assignee. Renovate adds an assignee after the PR is created and therefore tends to trip our PR rule (rfc13). 
Here's an example: https://github.com/artsy/reaction/pull/2350
Fixes #110.

don't fail prs on no assignee if renovate

---

org/jira/pr.ts

We got this error recently on a PR: https://github.com/artsy/reaction/pull/2355#issuecomment-490012229
```
Could not find './utils' as a relative import from artsy/peril-settings@org/jira/pr.ts. Does /org/jira/utils exist in the repo?
Error: Could not find './utils' as a relative import from artsy/peril-settings@org/jira/pr.ts. Does /org/jira/utils exist in the repo?
at /opt/out/runner/customGitHubRequire.js:54:11
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
--- 
No idea what changed to make this dynamic import suddenly fail. The paths in that error message are inconsistent and weird-looking so that probably warrants further investigation.
As a quick fix I made the import static, since there's no reason to be using a dynamic import here anyway.

Use normal import for utils

---

peril.settings.json

Doing a little one-two punch here - I'd like to use this PR to test if the review reminder implemented in [#116](https://github.com/artsy/peril-settings/pull/116) works, so please don't review this PR for a day and we'll see if you get a reminder!
And the actual content of the PR is a little thing that I missed when originally updating the `peril.settings.json` file - there was already a specific rule for the `peril-settings` repo and I added a second one. There's a chance that this will break the test because only one of them gets run, but let's see if the reminder gets sent first before jumping to that conclusion.

Consolidate peril-settings peril rule

---

org/ossPRsForbidForks.ts
peril.settings.json
tests/ossPRsForbidForks.test.ts

Following up on https://github.com/artsy/README/pull/218#discussion_r292960891 …
This changes some filenames / variable names to convey that OSS repos generally (and not just mobile repos) may make use of the Peril check to warn about PRs from forks.

Use more generic names for non-forking OSS repos

---

tasks/closedSourceRationaleCheck.ts

While talking through this with @ashfurrow over on https://github.com/artsy/Artsy-UIFonts/issues/9, we thought it might make sense to add this bit of troubleshooting to see if we can pinpoint what's going on here.

Add debug for empty readmes

---

org/addPatchLabel.ts
tests/rfc_reaction_1095.test.ts

On repos that use [auto](https://github.com/intuit/auto) we want to ensure that if the PR was created by dependabot that the PR gets assigned a `Version: Trivial` label instead of `Version: Patch`. 
Generally we don't consider dependency updates a good reason to update by themselves. This defaults to a label that won't trigger a release.

Add trivial label on dependabot PRs

---

org/markAsMergeOnGreen.ts
tests/rfc_10.test.ts

[Discussed on Slack](https://artsy.slack.com/archives/C2MEQ2HA6/p1563827563005200).
Peril reads comments and PR reviews for the phrase "merge on green" to mark a PR as needing to be merged when CI is green. The problem is, there's nothing about the phrase "merge on green" that indicates that you're directing _Peril_, instead of the engineer. 
This PR changes the words Peril search for to a hashtag: `#mergeongreen`. This hashtag format mirrors the other use of Peril looking for text:
https://github.com/artsy/peril-settings/blob/868d4ba97dbe3f268c84135abbb707b537b95a01/org/allPRs.ts#L70-L73
And we use a similar convention with Danger in a few repos, for example:
https://github.com/artsy/emission/blob/3ab51744d52cf7e4410d36e2f46c3a6019bb0a93/dangerfile.ts#L18-L20
---
This PR is marked `⚠️ DO …

⚠️ DO NOT MERGE YET ⚠️ Moves to hashtag #mergeongreen 

---

org/allPRs.ts
org/deploySummary.ts
tests/deploySummary.test.ts

This rather aggressively adds a peril rule simultaneously with the corresponding RFC https://github.com/artsy/README/issues/238 . I forgot about our RFC process when deciding to work on this for Future Fursday 😅 .
I was able to include this rule in a sample project, and run it as a danger rule. This seemed to work and produce the desired output on deploy PR's, while skipping non-deploy PR's.
So, assuming the RFC is agreed on, this is that implementation.
I'll add some tests as well.

@ashfurrow => Adds rule to generate nice deploy summary #FF

---

org/allPRs.ts

Right now some of the PR summary can kind of blend together and is a little hard to scan. Turning it into a list should add a little visual separation.
Before
After

Format PRs to a list for easier scanning

---

org/allPRs.ts
tests/deploySummary.test.ts

Good call @ashfurrow on calling out the potential perf. issue.
This switches to use the GraphQL endpoint to get all the relevant PR's, for all the included commits, in one request.
Closes https://github.com/artsy/peril-settings/issues/136

@zephraph => [deploySummary] Switches to use GraphQL endpoint to get all data in 1 req.

---

org/closedPRs.ts
org/jira/pr.ts

We've started seeing tickets that are already one, go back to merged column when they get deployed.
Ignore moving `done` and `closed` tickets.

Ignore Jira tickets that are already in Done column

---

tasks/standupReminder.ts
tests/standupReminder.test.ts

Fixes https://artsyproduct.atlassian.net/browse/OCWG-25 to move responsibility for running standup to the engineer _leaving_ on call, instead of both engineers _currently_ on call. 
@xtina-starr this means you'll be running next week's standup as well 🌟 
There were no unit tests to update for this change. We were previously rolling ahead a day to find out who was going to be on-call, so we just took that roll ahead out.

[OCWG-25] Moves standup responsibility to an engineer who is leaving on-call

---

peril.settings.json

Problem
In https://github.com/artsy/metaphysics/pull/2437/commits/39b06c0a955a7a036312003ac0765658497852ef, we updated our MP tooling so that we compare against the Force GraphQL schema, instead of Reaction's, now that Reaction has been merged into Force. 
As such, recent MP PRs have had breaking building due to peril-artsy not being able to find compareReactionSchema, for example: https://github.com/artsy/metaphysics/pull/2438
Moreover, whatever value that this comparison script is providing is minimized as the script wasn't running.
Solution
* Rename script in peril settings

Rename compareReactionSchema -> compareForceSchema

---

org/rfc_237.ts
peril.settings.json
tests/rfc_327.test.ts

Link to RFC: https://github.com/artsy/README/issues/327 and Conventional Commits: https://www.conventionalcommits.org
Planning to test this out with one repository (TBD: maybe this repository, peril-settings).
Also thinking of extending this rule to include PR commit linting as an alternative to using semantic formatting in the PR title.

feat: warn when semantic formatting not detected in PR title

---

org/rfc_237.ts

I don't think this check is picked up correctly by Peril without this default export defined.

chore: Add default export to rfc_327

---

peril.settings.json

Experimenting with a GitHub Action + Artsy CLI approach.
- https://github.com/artsy/README/pull/367
- https://github.com/artsy/artsy-cli/pull/24

chore: remove monday informationals scheduled task

---

org/allPRs.ts
tests/rfc_327.test.ts

This comes as a follow-up from our Knowledge share yesterday.

feat: Enable conventional commits for titles on Eigen

---

org/allPRs.ts

This link to the original RFC creates a lot of noise on the [GitHub issue][issue]. This commit removes the link to eliminate that noise.
[issue]: https://github.com/artsy/README/issues/327
cc/ @admbtlr @patrinoua

chore: remove RFC link from automated Peril semantic commit formatting comment

---

org/allPRs.ts

Follow up to https://github.com/artsy/peril-settings/pull/194 which still creates an undesired backlink on the original RFC GitHub issue.

chore: really remove the link to README#327 RFC

---

org/allPRs.ts

This PR adds `revert` as an accepted semantic commit type. 
Relevent conversation: https://github.com/artsy/README/pull/478/files#r942090914

feat: add revert as accepted commit type

---

org/allPRs.ts

This PR disables semantic commit check on Deploy PRs
The goal is to avoid this type of message

fix: disable semantic commit check on Deploy PRs

---

package.json
spellcheck.json
yarn.lock

Use `ignoreFiles` instead of `whitelistFiles`. Thanks @gkartalis for [this contribution](https://github.com/orta/danger-plugin-spellcheck/pull/31)
Follow-up from:
- https://github.com/artsy/peril-settings/issues/190

chore: adopt inclusive content for spellcheck

---

org/allPRs.ts
tests/rfc_327.test.ts

Makes our conventional commits rule more forceful:
- apply across all repos - excluded repos added if we need exceptions
- fail prs rather than nudge

feat: conventional commits everywhere

---

org/allPRs.ts
tests/rfc_327.test.ts

This has been bothering me on my prs: https://github.com/artsy/gravity/pull/18001
Just adds an exception for check for common wip prefixes.

feat: exclude wip prs from conventional commit check

---

peril.settings.json

Removing tasks that were found to be broken or no longer applied to any repos in a [recent audit](https://docs.google.com/document/d/1MS9Rpq9o6RwOnuOEEPJv9mwGngY1edQjabwPR3QmN6E/edit?usp=sharing).

chore: remove unused or broken settings

---

org/rfc/scheduleRFCsForLabels.ts
tests/rfc_40.test.ts

**Context:**
Over the past few weeks, we have been receiving a reminder about closing an already closed issue:
This PR fixes that by making sure to check first if the issue is still open or not. We do something similar here
https://github.com/artsy/peril-settings/blob/e667b7ecc6ab167e5631d0fd981bf69216b5fd5a/org/rfc/scheduleRFCsForLabels.ts#L29

fix: do not alert on closed RFC issues

---

peril.settings.json

Peril and Github Actions on PRs have been running in parallel for over a week now and I haven't heard any complaints, so I think we're good to remove Peril running the same dangerfiles in **metaphysics**, **volt**, and **exchange**. We checked the other repos in the list and they were just running checks that Peril is already doing anyway, so we didn't migrate anything for those.

refactor: remove unused or migrated peril settings
